import Ember from 'ember';
let personnel = [{
  id: '134',
  firstName: 'Mike',
  lastName: 'X',
  yrs: '5',
  rank: 'Officer',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Officer',
  unit: 'EOD'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '980',
  firstName: 'Juan',
  lastName: 'Lee',
  yrs: '4',
  rank: 'Enlisted',
  unit: 'Diving'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}, {
  id: '345',
  firstName: 'Test',
  lastName: 'New',
  yrs: '7',
  rank: 'Enlisted',
  unit: 'Boat'
}]

export default Ember.Route.extend({
  model() {
    return personnel;
  }
});
